name: Master Helm Deployemnt 
on:
  # workflow_dispatch:
  #   inputs:
  #     chartversion:
  #       description: 'Chart Version'     
  #       required: true
  #       default: ''
  push:
   branches: [ main ]
  # pull_request:
  #  branches: [ main ]  
      
jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node: [ 14, 16, 18 ]
    name: Argocd app deployment
    steps:
      - name: Gitclone
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          
      - name: Configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr   

      - name: Build docker Image and Push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.DOCKER_IMAGE_REPO }}
          IMAGE_TAG: $(echo ${{ github.sha }} | head -c 8)
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }} .
          docker push $REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }}

      - name: Configure the deployment file
        # env:
        #   IMAGE_TAG: $(echo ${{ github.sha }} | head -c 8)  
        run: |
          cat manifest/deployment.yaml
          chart_dir="manifest"
          IMAGE_TAG=$(echo ${{ github.sha }} | head -c 8)
          sed -i 's/^ *image: .*/  image: node-app:${IMAGE_TAG}/' manifest/deployment.yaml
          cat manifest/deployment.yaml 
      - name: Commit the changes made
        run: | 
          git config --global user.name "arunodhayamsam"
          git config --global user.email "100224916+arunodhayamsam@users.noreply.github.com"
          git commit -am "updating image tag"
          git push
      # - name: Configure the deployment file
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: ${{ secrets.DOCKER_IMAGE_REPO }} 
      #     IMAGE_TAG: $(echo ${{ github.sha }} | head -c 8)
      #   run: |
      #     DOCKER=$REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }}
      #     VERSION_ID=${{ github.event.inputs.chartversion}}
      #     sed -i 's@VERSION@'"$VERSION_ID"'@' eks-charts/Chart.yaml
      #     sed -i 's@CONTAINER_IMAGE@'"$DOCKER"'@' eks-charts/values.yaml
      #     cat eks-charts/Chart.yaml
      #     cat eks-charts/values.yaml

      # - name: Deploy Helm
      #   uses: bitovi/github-actions-deploy-eks-helm@v1.2.3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     cluster-name: ${{ secrets.CLUSTER_NAME }}
      #     chart-path: eks-charts/
      #     namespace: master
      #     name: node-app-helm-prod

      # - name: Package and push helm chart to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: ${{ secrets.HELM_REPO }}
      #   run: |
      #     VERSION_ID=${{ github.event.inputs.chartversion}}
      #     helm package $REPOSITORY
      #     helm push $REPOSITORY-$VERSION_ID.tgz oci://$REGISTRY    